stages:
  - build

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build:jdk17:
  stage: build
  tags:
    - build
  script:
    - './mvnw install:install-file -Dfile=libext/yeti-annotations.jar -DgroupId=com.arkham -DartifactId=annotations -Dversion=1.0 -Dpackaging=jar'
    - './mvnw install:install-file -Dfile=libext/ojdbc-12.2.jar -DgroupId=com.oracle -DartifactId=driver -Dversion=12.2 -Dpackaging=jar'
    - './mvnw install:install-file -Dfile=libext/orai18n-12.2.jar -DgroupId=com.oracle -DartifactId=i18n -Dversion=12.2 -Dpackaging=jar'
    - './mvnw install:install-file -Dfile=libext/arkham-common-1.1.jar -DgroupId=com.arkham -DartifactId=common -Dversion=1.1 -Dpackaging=jar'
    - './mvnw $MAVEN_CLI_OPTS package'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
